// src/components/Footer.vue
<script setup>
import {defineComponent, h} from "vue";

const navigation = [
  {
    name: 'GitHub',
    href: 'https://github.com/FABKIT/FABKIT',
    icon: defineComponent({
      render: () =>
          h('svg', { fill: 'currentColor', viewBox: '0 0 24 24' }, [
            h('path', {
              'fill-rule': 'evenodd',
              d: 'M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z',
              'clip-rule': 'evenodd',
            }),
          ]),
    }),
  },
]
</script>

<template>
  <footer class="dark:bg-dark sticky top-[100vh] pt-3 border-t border-t-primary">
    <div class="mx-auto max-w-7xl px-6 md:flex md:items-center md:justify-between lg:px-8">
      <div class="flex justify-center gap-x-6 md:order-2">
        <a v-for="item in navigation" :key="item.name" :href="item.href" class="text-primary hover:text-gray-400">
          <span class="sr-only">{{ item.name }}</span>
          <component :is="item.icon" class="size-6" aria-hidden="true" />
        </a>
      </div>
      <div>
        <p class="mt-8 text-left text-sm/6 text-primary md:order-1 md:mt-0">FABKIT is in no way affiliated with Legend Story Studios. Legend Story Studios®, Flesh and Blood™, and set names are trademarks of Legend Story Studios. Flesh and Blood characters, cards, logos, and art are property of Legend Story Studios. Card Images © Legend Story Studios</p>
        <p class="mt-8 text-left text-sm/6 text-primary md:order-1 md:mt-0">Developed by Thencros & Lambstream</p>
      </div>
    </div>
  </footer>
</template>

<style scoped>

</style>

// src/components/layout/Footer.tsx
import type { ComponentType, SVGProps } from "react";
import { useTranslation } from "react-i18next";
import { Bluesky } from "../icons/Bluesky.tsx";
import { Discord } from "../icons/Discord.tsx";
import { Github } from "../icons/Github.tsx";

type NavItem = {
	name: string;
	href: string;
	icon: ComponentType<SVGProps<SVGSVGElement>>;
};

const navigation: NavItem[] = [
	{
		name: "GitHub",
		href: "https://github.com/FABKIT/FABKIT",
		icon: Github,
	},
	{
		name: "Discord",
		href: "https://discord.gg/4twcdby9xp",
		icon: Discord,
	},
	{
		name: "Bluesky",
		href: "https://bsky.app/profile/teamfabkit.bsky.social",
		icon: Bluesky,
	},
];

export function Footer() {
	const { t } = useTranslation();

	return (
		<footer className="sticky top-[100vh] z-10 border-t border-t-primary bg-surface pt-3 lg:pl-72">
			<div className="mx-auto max-w-7xl px-6 pb-5 md:flex md:items-center md:justify-between lg:px-8">
				<div className="flex justify-center gap-x-6 md:order-2">
					{navigation.map((item) => (
						<a
							key={item.name}
							href={item.href}
							className="text-primary hover:text-gray-400"
						>
							<span className="sr-only">{item.name}</span>
							<item.icon className="size-6" aria-hidden="true" />
						</a>
					))}
				</div>
				<div>
					<p className="mt-8 text-left text-sm/6 text-primary md:order-1 md:mt-0">
						{t("footer.disclaimer")}
					</p>
					<p className="mt-8 text-left text-sm/6 text-primary md:order-1 md:mt-0">
						{t("footer.credits")}
					</p>
				</div>
			</div>
		</footer>
	);
}
