// src/apps/card-creator/components/home/FeaturedArtist.tsx
import { ArrowRight, ChevronLeft, ChevronRight, Star } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { useTranslation } from "react-i18next";
import Contact from "@fabkit/platform/config/contact.ts";
import { featuredArtists } from "../../config/featured_artist.tsx";

export function FeaturedArtist() {
	const { t } = useTranslation("card-creator");
	const [currentSlide, setCurrentSlide] = useState(0);
	const featuredArtist =
		featuredArtists[Math.floor(Math.random() * featuredArtists.length)];

	const nextSlide = useCallback(() => {
		setCurrentSlide((prev) => (prev + 1) % featuredArtist.images.length);
	}, [featuredArtist.images.length]);

	const prevSlide = useCallback(() => {
		setCurrentSlide(
			(prev) =>
				(prev - 1 + featuredArtist.images.length) %
				featuredArtist.images.length,
		);
	}, [featuredArtist.images.length]);

	useEffect(() => {
		const intervalId = setInterval(nextSlide, 7000);
		return () => clearInterval(intervalId);
	}, [nextSlide]);

	return (
		<div className="mx-auto max-w-[1600px] overflow-hidden rounded-lg border-2 border-border-primary bg-surface/50 shadow-lg backdrop-blur-sm">
			<div className="flex flex-col items-start gap-6 p-6 lg:gap-8 xl:flex-row">
				{/* Left side: Image slideshow with header on mobile/tablet */}
				<div className="flex w-full flex-col gap-4 xl:w-auto">
					{/* Featured Artist header - shows above card on mobile/tablet */}
					<div className="space-y-2 text-center xl:hidden">
						<div className="inline-flex items-center gap-2 text-sm font-semibold text-heading">
							<Star className="h-5 w-5" />
							<span>{t("components.featured_artist.label")}</span>
						</div>
						<h3 className="text-2xl font-bold text-heading">
							{featuredArtist.name}
						</h3>
						<p className="text-sm italic text-muted">
							"{featuredArtist.collection}"
						</p>
					</div>

					<div className="flex items-center justify-center gap-3">
						<button
							type="button"
							aria-label={t("components.featured_artist.previous_slide")}
							className="shrink-0 rounded-full border-2 border-border-primary bg-surface p-2 shadow-lg transition-transform hover:scale-110"
							onClick={prevSlide}
						>
							<ChevronLeft className="h-6 w-6 text-primary" />
						</button>

						<div className="relative aspect-[450/628] w-full max-w-[450px] overflow-hidden rounded-lg lg:w-[450px]">
							{featuredArtist.images.map((image, index) => (
								<img
									key={image}
									src={image}
									alt={`${t("components.featured_artist.card_alt")} ${index + 1}`}
									className="absolute inset-0 h-full w-full object-contain transition-opacity duration-500"
									style={{ opacity: currentSlide === index ? 1 : 0 }}
								/>
							))}
						</div>

						<button
							type="button"
							aria-label={t("components.featured_artist.next_slide")}
							className="shrink-0 rounded-full border-2 border-border-primary bg-surface p-2 shadow-lg transition-transform hover:scale-110"
							onClick={nextSlide}
						>
							<ChevronRight className="h-6 w-6 text-primary" />
						</button>
					</div>

					<div className="flex justify-center gap-2">
						{featuredArtist.images.map((image, index) => (
							<button
								key={image}
								type="button"
								aria-label={`${t("components.featured_artist.go_to_slide")} ${index + 1}`}
								className={`h-2 rounded-full transition-all ${
									currentSlide === index
										? "w-6 bg-primary"
										: "w-2 bg-gray-400 hover:bg-gray-500"
								}`}
								onClick={() => setCurrentSlide(index)}
							/>
						))}
					</div>
				</div>

				{/* Right side: Description */}
				<div className="flex flex-col justify-center space-y-4 xl:min-w-0 xl:flex-1">
					<div className="hidden space-y-2 xl:block">
						<div className="inline-flex items-center gap-2 text-sm font-semibold text-heading">
							<Star className="h-5 w-5" />
							<span>{t("components.featured_artist.label")}</span>
						</div>
						<h3 className="text-2xl font-bold text-heading">
							{featuredArtist.name}
						</h3>
						<p className="text-sm italic text-muted">
							"{featuredArtist.collection}"
						</p>
					</div>

					<div className="space-y-4 text-body leading-relaxed">
						{featuredArtist.description}
					</div>

					<div className="space-y-2 pt-2">
						<a
							href="https://discord.com/invite/vMRMdqJc4V"
							target="_blank"
							rel="noreferrer"
							className="inline-flex items-center gap-2 text-sm font-semibold text-heading hover:underline"
						>
							{t("components.featured_artist.fab_discord_link")}
							<ArrowRight className="h-4 w-4" />
						</a>
					</div>
					<div>
						<a
							href={Contact.DiscordInvite}
							target="_blank"
							rel="noreferrer"
							className="inline-flex items-center gap-2 text-sm font-semibold text-heading hover:underline"
						>
							{t("components.featured_artist.our_discord_link")}
							<ArrowRight className="h-4 w-4" />
						</a>
					</div>
				</div>
			</div>
		</div>
	);
}

// src/components/FeaturedArtist.vue
<script setup>
import {ref, onMounted, onUnmounted} from 'vue'
import {ChevronLeftIcon, ChevronRightIcon, StarIcon} from '@heroicons/vue/24/solid'

const artist = {
  name: 'Artist name',
  collection: 'Collection Title',
  description: `
        <p class="text-primary/80 dark:text-white/80 leading-relaxed">
          Winner of our Custom Card Contest hosted on the <a href="https://discord.gg/fabdb" target="_blank" class="text-primary dark:text-white underline hover:no-underline">Flesh and Blood TCG Discord</a>! These stunning cards showcase the incredible creativity possible with FABKIT's card creator.
        </p>

        <p class="text-primary/80 dark:text-white/80 leading-relaxed">
          [Add 1-2 more sentences about the artist's style, their inspiration, or what makes their cards special]
        </p>

        <div class="pt-2">

          <a href="https://discord.gg/4twcdby9xp"
          target="_blank"
          class="inline-flex items-center gap-2 text-sm font-semibold text-primary dark:text-white hover:underline"
          >
          Join our Discord to participate in future contests
          <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 8l4 4m0 0l-4 4m4-4H3"/>
          </svg>
          </a>
        </div>`,
  images: [
    '/src/assets/featuredartist/Featured_Artist_1.png',
    '/src/assets/featuredartist/Featured_Artist_2.png',
    '/src/assets/featuredartist/Featured_Artist_3.png',
    '/src/assets/featuredartist/Featured_Artist_4.png',
    '/src/assets/featuredartist/Featured_Artist_5.png',
    '/src/assets/featuredartist/Featured_Artist_6.png',
    '/src/assets/featuredartist/Featured_Artist_7.png',
  ],
};

const currentSlide = ref(0)
let intervalId = null

const nextSlide = () => {
  currentSlide.value = (currentSlide.value + 1) % artist.images.length
}

const prevSlide = () => {
  currentSlide.value = (currentSlide.value - 1 + artist.images.length) % artist.images.length
}

const goToSlide = (index) => {
  currentSlide.value = index
}

onMounted(() => {
  // Auto-advance slides every 4 seconds
  intervalId = setInterval(nextSlide, 4000)
})

onUnmounted(() => {
  if (intervalId) {
    clearInterval(intervalId)
  }
})

</script>

<template>
  <div class="rounded-lg shadow-lg border-2 border-primary/20 overflow-hidden max-w-[1600px] mx-auto backdrop-blur-sm bg-white/20 dark:bg-dark/50">
    <div class="flex flex-col xl:flex-row gap-6 lg:gap-8 p-6 items-start">
      <!-- Left side: Image slideshow with header on mobile/tablet -->
      <div class="flex flex-col gap-4 w-full xl:w-auto">
        <!-- Featured Artist header - shows above card on mobile/tablet -->
        <div class="xl:hidden space-y-2 text-center">
          <div class="inline-flex items-center gap-2 text-sm font-semibold text-primary dark:text-white">
            <StarIcon class="w-5 h-5"/>
            <span>Featured Artist</span>
          </div>
          <h3 class="text-2xl font-bold text-primary dark:text-white">
            {{ artist.name }}
          </h3>
          <p class="text-sm text-primary/70 dark:text-white/70 italic">
            "{{ artist.collection }}"
          </p>
        </div>

        <div class="flex items-center gap-3 justify-center">
          <!-- Left Arrow -->
          <button
            aria-label="Previous slide"
            class="flex-shrink-0 bg-white dark:bg-dark p-2 rounded-full shadow-lg hover:scale-110 transition-transform border-2 border-primary/20"
            @click="prevSlide"
          >
            <ChevronLeftIcon class="w-6 h-6 text-primary"/>
          </button>

          <div class="relative w-full max-w-[450px] lg:w-[450px] bg-gray-100 dark:bg-gray-800 rounded-lg overflow-hidden aspect-450/628">
            <div class="relative w-full h-full">
              <transition-group name="fade">
                <img
                  v-for="(image, index) in artist.images"
                  v-show="currentSlide === index"
                  :key="index"
                  :alt="`Custom card ${index + 1}`"
                  :src="image"
                  class="absolute inset-0 w-full h-full object-contain"
                />
              </transition-group>
            </div>
          </div>

          <button
            aria-label="Next slide"
            class="flex-shrink-0 bg-white dark:bg-dark p-2 rounded-full shadow-lg hover:scale-110 transition-transform border-2 border-primary/20"
            @click="nextSlide"
          >
            <ChevronRightIcon class="w-6 h-6 text-primary"/>
          </button>
        </div>

        <div class="flex justify-center gap-2">
          <button
            v-for="index in artist.images.keys()"
            :key="`dot-${index}`"
            :aria-label="`Go to slide ${index + 1}`"
            :class="[
              'w-2 h-2 rounded-full transition-all',
              currentSlide === index
                ? 'bg-primary w-6'
                : 'bg-gray-400 hover:bg-gray-500'
            ]"
            @click="goToSlide(index)"
          />
        </div>
      </div>
      <div class="flex flex-col justify-center space-y-4 xl:flex-1 xl:min-w-0">
        <div class="hidden xl:block space-y-2">
          <div class="inline-flex items-center gap-2 text-sm font-semibold text-primary dark:text-white">
            <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
              <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"/>
            </svg>
            <span>Featured Artist</span>
          </div>
          <h3 class="text-2xl font-bold text-primary dark:text-white">
            {{ artist.name }}
          </h3>
          <p class="text-sm text-primary/70 dark:text-white/70 italic">
            "{{ artist.collection }}"
          </p>
        </div>
        <div v-html="artist.description"></div>
      </div>
    </div>
  </div>
</template>

<style scoped>
.fade-enter-active, .fade-leave-active {
  transition: opacity 0.5s ease;
}

.fade-enter-from, .fade-leave-to {
  opacity: 0;
}

.fade-enter-to, .fade-leave-from {
  opacity: 1;
}
</style>
